---
title: "Spatial Distribtuion of Urban Tree Species"
author: "Eli Robinson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Abstract
This study aimed to understand if there was a connection between tree species and income levels in urban areas across ten different cities in the US, using data from the Urban Forest Inventory and Analysis (FIA) dataset and census block group information from the 2020 US Census Bureau American Community Survey. The FIA dataset provides detailed information on urban trees, including diameter, height, condition, biomass, and species. The study used spatial analysis to associate each tree with the average household income of the surrounding neighborhood. The results showed that the five most common tree species in each city correlated differently with the mean local income, with some species appearing more frequently in high-income areas, while others were more common in low-income areas. The study identified potential limitations of the methodology, such as areas with no people living, and highlighted the need for more research to address these limitations. The findings of this study can inform policy decisions and resource allocation aimed at reducing ecological inequality in urban areas.

## Introduction

Trees have a major effect on cities being able to reduce urban heat island effect, mitigate air pollution, improve drainage, and provide health benefits to humans (Speak, 2018; Wolf, 2020). Every tree however, provides different services at different levels. Each tree species provides a different value of ecosystem service to the environment it is in and specific tree species are often overlooked when urban tree studies are performed. It is important to understand the spatial distribution of these urban trees across urban areas and across different socioeconomic groups in order to understand if there is inequality in a city based on urban trees in order to inform policy makers and allocate resources in order to prevent this ecological inequality.

Previous research has been done in this area of study including studies that measured canopy cover related to urban heat (Mcdonald, 2021). This study measured the differences between overall tree cover and urban heat and found that with less tree cover there is more heat. Then expanded that to include socioeconomic factors as well. Another study measured green spaces compared to socioeconomic conditions (Li, 2015) and found that areas in worse socioeconomic conditions have less green spaces or green values. Both of these studies and similar other studies use satellite imagery, The first through landsat imagery and the second through google imagery. These methods are good for getting an overall picture but sometimes can miss specific details and key information such as tree species. Based on previous work of the FIA which mapped forests, this program is now working to collect data for trees in urban areas which is the main focus of this study.

## Methods

Two data sets that were used for this study: the first is census block group information from 2020 US Census Bureau American Community Survey (Manson, 2022) focusing on average household income. Census block group is the finest resolution data that has the average household income so that it was used for this study.

The Urban Forest Inventory and Analysis (FIA) dataset (Edgar, 2021) is a relatively new dataset of urban trees. This dataset differs from the previous because instead of collecting the data with satellite imagery, data is collected by surveyors on the ground. This allows for additional information to be collected including diameter of a tree, height, calculated biomass, condition of tree, and tree species. Tree species were used in this study in order to understand if different tree species appear more frequently in high and low income areas. This is the first federal program which conducts representative studies and data collection. This data set contains a set of tree and plot data that contains information about urban trees including location, species, condition, and much more with both measured and calculated values. This dataset has information for 10 cities (Austin, TX; Chicago, IL; Houston, TX; Kansas City, MO; Portland, OR; San Antonio, TX; San Diego, CA; Springfield, MO; St. Louis, MO; Washington DC) across the US which will be the areas of focus for this study.

The goal of the project was to associate each tree with a local income from the data of surrounding neighborhoods. In order to do this The Urban FIA data has trees within plots, which have location values associated with them. In order to conduct spatial analysis on tree information it is necessary to combine this information at some point. First, however, we must find the average household income associated with each plot. The divulged coordinates of FIA plots are only accurate to within 1 km. To account for this, we buffered each plot by 1 km. We intersected the resulting buffer with the census block groups and averaged the income, weighted by the census block group area that was within the buffer. Then dissolve by plot. This results in the area of the buffered plot with the information of the weighted local census information. The final step is to merge the plots back to the trees. This gives each tree both a geometry of their plot location and the average household income of the nearby block groups. 
The final result is a dataset of trees which has species name from the original dataset and local income value from the spatial analysis.

## Results

In order to display results we plotted the 5 most common tree species in a city by the mean local income found via the spatial analysis. This will give an understanding of some of the common tree species in each city and how they relate to the local income.


These first two graphs of Austin, Texas and San Antonio, Texas are quite similar. Four of the five most common trees in the city are shared between the two, and each show similar results, with sugar berry on the low end, cedar elm towards the middle of the income and, ashe juniper and live oak towards the higher end of the average local income. The graph of San Antonio shows one potentially large error with the methodology that should be resolved with future work. There are a few trees at a zero value for mean local income. This is not due to being in an area where people do not earn money but rather the trees are in areas where there are no people living. This could be business districts that are not zoned for living, parks and natural lands, or government buildings that have a relatively small block group size.

When looking at the graph of Springfield, Missouri there are two things that stand out. The first is that all five of the common trees appear to be in the same income brackets. The other is that due to Springfield being a small city the mean local incomes of this city are much lower than some of the other cities that have been shown.

In Washington D.C. there is a difference between the common tree species with many american beech trees in wealthy areas and red maples and white oak in the lower income areas. This graph shows a good spread between all of the different species.

## Discussion

The results of this study provide valuable insights into the relationship between income and tree species in urban areas. While similar studies have found that income is often a predictor of tree cover, with low-income neighborhoods having less tree cover than higher-income neighborhoods, these results are able to dive deeper into the nuance of tree species. In these urban areas by showing that certain tree species tend to be more common in high-income areas, while other species are more commonly found in low-income areas.

All trees are not the same and different species of trees provide different ecosystem services. (Do you think I should give specific examples?) Some trees provide more drainage, or shade, or other factors and different trees will affect the ecosystem and the city in different ways. These findings are particularly interesting because they shed light on potential inequities in urban forestry and urban tree management and could highlight the need for a more equitable distribution of trees. Understanding the patterns of inequities is crucial for improving environmental and social equity in urban areas.

One of the species that commonly appear in low income areas, especially in Texas, is the sugarberry tree. The sugarberry tree is a tree that is native to the southeast United States and is a short to medium sized tree that grows fast and can grow in a variety of soil types and conditions. This makes the sugarberry a very opportunistic tree as it is able to gain hold and grow in a variety of environments. The sugar berry tree being a small tree provides less tree cover, and environmental benefits than a larger and potentially more desirable tree. One such tree that appears in these Texas urban environments is the live oak tree. The live oak tree is a deep rooted species which can help prevent erosion, and its larger size in width and increased leaf areas provide additional tree cover.

One possible explanation for these patterns is that tree planting and maintenance programs may be more common in higher-income neighborhoods. Additionally, preferences for certain tree species may differ among different income groups. For example, some high-income neighborhoods may prefer to plant ornamental trees for aesthetic purposes, while low-income neighborhoods may prioritize trees that provide more tangible benefits such as shade and improved air quality.

The implications of these findings are significant. Different trees provide a wider range of benefits such as improved air quality, reduced energy use, and enhanced mental health. However, not all communities have equal access to these benefits. By identifying and addressing potential inequities in tree cover, we can work towards creating more sustainable and equitable urban environments.

Future research could further explore the underlying casues of these patterns and identify potential solutions for improving equitable access to trees in urban areas. Additionally, continued monitoring and data collection efforts such as the Urban FIA program can help inform management and policy decisions.


## Future Work + Conclusion

Some future research can be done based off of this work. One thing that could be done is to fully map out the ecosystem service and disservice of each tree species. This could be done by creating a model based on literature such as Bolund, 2017 and other papers which can help to determine how valuable a tree is to the urban environment based on a variety of factors. This could assign some kind of tree service disservice value and help to better understand a connection between ecosystem services and disservice that is more in depth than tree species.

Another piece of research that could be done is to use different information within the FIA data. The Urban FIA data has many different variables which are all interesting and could each have individual studies on them. These studies could also make more sense across a broader scope of cities as tree species are generally most determined by environment rather than other factors such as tree height or condition, which are affected but not drastically different city by city.

In conclusion, the socioeconomic patterns of urban tree species provide valuable insights into the complex relationship between cities and nature. By examining what different tree species are distributed across urban areas and their correlation with various socioeconomic factors, we can gain a deeper understanding of the ways in which urban trees impact an urban ecosystem. This information can inform urban planning and management strategies, allowing us to create more equitable and sustainable urban environments.

## Works Cited

Andrew Speak, Francisco J. Escobedo, Alessio Russo, Stefan Zerbe, An ecosystem service-disservice ratio: Using composite indicators to assess the net benefits of urban trees, Ecological Indicators, Volume 95, Part 1, 2018, Pages 544-553, ISSN 1470-160X, https://doi.org/10.1016/j.ecolind.2018.07.048.

Edgar, Christopher B, et al. “Strategic National Urban Forest Inventory for the United States.” Journal of Forestry, vol. 119, no. 1, 2020, pp. 86–95, https://doi.org/10.1093/jofore/fvaa047. 

McDonald RI, Biswas T, Sachar C, Housman I, Boucher TM, Balk D, et al. (2021) The tree cover and temperature disparity in US urbanized areas: Quantifying the association with income across 5,723 communities. PLoS ONE 16(4): e0249715. https://doi.org/10.1371/journal.pone.0249715

Steven Manson, Jonathan Schroeder, David Van Riper, Tracy Kugler, and Steven Ruggles. IPUMS National Historical Geographic Information System: Version 17.0 [dataset]. Minneapolis, MN: IPUMS. 2022. http://doi.org/10.18128/D050.V17.0

Wolf KL, Lam ST, McKeen JK, Richardson GRA, van den Bosch M, Bardekjian AC. Urban Trees and Human Health: A Scoping Review. International Journal of Environmental Research and Public Health. 2020; 17(12):4371. https://doi.org/10.3390/ijerph17124371

Xiaojiang Li, Chuanrong Zhang, Weidong Li, Yulia A. Kuzovkina, Daniel Weiner, Who lives in greener neighborhoods? The distribution of street greenery and its association with residents’ socioeconomic conditions in Hartford, Connecticut, USA, Urban Forestry & Urban Greening, Volume 14, Issue 4, 2015, Pages 751-759, ISSN 1618-8667, https://doi.org/10.1016/j.ufug.2015.07.006.


